name: Fetch JSON Data

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch JSON Data
        run: |
          python3 -m pip install requests
          python3 fetch_json.py "https://github.com/mitthu786/tvepg/raw/main/tataplay/tsdataWc.json" "https://github.com/mitthu786/tvepg/raw/main/tataplay/tsdata.json"  # Pass URLs directly
